language: node_js

node_js:
  - "10"

notifications:
  email: false

install:
  npm install

cache:
  directories:
    - "node_modules"

script:
  - npm run test:unit
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: dist
  on:
    branch: master
